// src/components/layouts/friends.tsx
"use client";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Card, CardContent } from "@/components/ui/card";
import { FriendsConfig } from "@/config";
import { motion } from "framer-motion";
import { useTranslations } from "next-intl";
import Link from "next/link";
import React, { useEffect, useState } from "react";

interface FriendsProps {
	friends: Friend[];
}

export const FriendsLayout: React.FC<FriendsProps> = ({ friends }) => {
	const t = useTranslations();
	const [shuffledFriends, setShuffledFriends] = useState<Friend[]>([]);

	useEffect(() => {
		const shuffleArray = (array: Friend[]) => {
			for (let i = array.length - 1; i > 0; i--) {
				const j = Math.floor(Math.random() * (i + 1))
                    ;[array[i], array[j]] = [array[j], array[i]];
			}
		};

		const newShuffledFriends = [...friends];
		shuffleArray(newShuffledFriends);
		setShuffledFriends(newShuffledFriends);

		// Add touch device support for hover effect
		const cards = document.querySelectorAll("#friend-card > *");
		cards.forEach((card) => {
			card.addEventListener("touchstart", () => {
				card.classList.add("group-hover");
			});
			card.addEventListener("touchend", () => {
				card.classList.remove("group-hover");
			});
		});

		return () => {
			cards.forEach((card) => {
				card.removeEventListener("touchstart", () => { });
				card.removeEventListener("touchend", () => { });
			});
		};
	}, [friends]);

	return (
		<div className="w-full mt-5 flex flex-col items-start mb-6 px-4 sm:px-6 lg:px-8">
			<motion.h1
				className="text-2xl sm:text-3xl lg:text-4xl font-bold mt-10"
				initial={{ opacity: 0, y: -50 }}
				animate={{ opacity: 1, y: 0 }}
				transition={{ duration: 0.5 }}
			>
				<mark className="line">{t(FriendsConfig.title)}</mark>
				<p className="mt-6 text-sm text-muted-foreground max-w-2xl">
					{t(FriendsConfig.description.text)}
					{" "}
					<Link
						href={FriendsConfig.description.link.url}
						target="_blank"
						className="underline text-[#3388BB] transition-all duration-300 ease-in-out hover:text-[#FF5522] hover:scale-110"
					>
						{t(FriendsConfig.description.link.text)}
					</Link>
					{" "}
					{t(FriendsConfig.description.suffix)}
				</p>
			</motion.h1>
			<div className="container mx-auto mt-2 px-4 py-12 flex flex-col items-center animate-in fade-in duration-500">
				<div
					id="friend-card"
					className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6"
				>

					{shuffledFriends.map(friend =>
						friend.hide === false && friend.state === 0
							? (
									<Card
										key={friend.id}
										className="relative overflow-hidden transition-all duration-300 hover:scale-105 active:scale-95 group"
									>
										<CardContent className="p-4">
											<a
												href={friend.url}
												target="_blank"
												rel="noopener noreferrer"
												className="block"
											>
												<div className="flex flex-col items-center">
													<Avatar className="w-20 h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 lg:w-32 lg:h-32 mb-3 sm:mb-4 transition-all duration-300 group-hover:opacity-40 group-hover:blur-sm rounded-full">
														<AvatarImage src={friend.avatar} alt={friend.name} />
														<AvatarFallback>{friend.name[0]}</AvatarFallback>
													</Avatar>
													<h3 className="text-base sm:text-lg font-semibold text-center">{friend.name}</h3>
												</div>
												<div
													id="friend-card-hover"
													className="absolute inset-0 flex flex-col items-center justify-center text-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-background/60 backdrop-blur-md p-4"
												>
													<h3 className="text-base sm:text-lg font-semibold mb-2">
														{friend.name}
													</h3>
													<p className="text-muted-foreground text-sm sm:text-base mb-2 sm:mb-4 line-clamp-3">
														{friend.description}
													</p>
													<p className="text-muted-foreground text-xs sm:text-sm mb-2 sm:mb-4 truncate max-w-full">
														{friend.url}
													</p>
													<div
														className="absolute inset-0 opacity-30 bg-cover bg-center group-hover:blur-md transition-all duration-300"
														style={{ backgroundImage: `url(${friend.avatar})` }}
													/>
												</div>
											</a>
										</CardContent>
									</Card>
								)
							: null,
					)}
				</div>
			</div>
		</div>
	);
};

export default FriendsLayout;

// src/layouts/Friends.vue
<script setup>
import { ref, onMounted } from 'vue';

const friends = ref([]);

onMounted(async () => {
    friends.value = await $fetch('/api/getFriends');
    shuffleArray(friends.value);
});

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}
</script>

<template>
    <div class="w-full flex justify-start mb-6">
        <h1 class="absolute text-4xl m-6"><mark class="line">友情链接</mark></h1>
    </div>
    <div class="container mx-auto mt-20 px-4 py-12 flex flex-col items-center animate-fade-in">
        <div id="friend-card" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div v-for="friend in friends" :key="friend.id" class="flex">
                <a v-if="!friend.hide" :href="friend.url" target="_blank"
                    class="relative bg-gray-100 dark:bg-gray-700 rounded-lg shadow-lg overflow-hidden transform transition-transform duration-300 hover:scale-105 hover:shadow-2xl group flex flex-col w-full p-4">
                    <div class="flex items-center justify-center relative transition-all duration-300 mb-4">
                        <span
                            class="relative flex shrink-0 overflow-hidden w-24 h-24 md:w-32 md:h-32 rounded-full border-4 border-gray-200 dark:border-gray-600 group-hover:opacity-0 transition-opacity duration-300">
                            <img class="aspect-square h-full w-full object-cover transition-transform duration-300 group-hover:scale-110 group-hover:blur-sm"
                                :alt="friend.name" :src="friend.avatar" />
                        </span>
                    </div>
                    <div class="text-center">
                        <h3 class="text-lg font-semibold text-gray-800 dark:text-gray-200">
                            {{ friend.name }}
                        </h3>
                    </div>
                    <div id="friend-card-hover"
                        class="absolute inset-0 flex flex-col items-center justify-center text-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gray-100 dark:bg-gray-700">
                        <h3 class="text-lg font-semibold mb-2 text-gray-800 dark:text-gray-200 mx-4">
                            {{ friend.name }}
                        </h3>
                        <p class="text-gray-800 dark:text-gray-600 text-base mb-4 mx-4">
                            {{ friend.description }}
                        </p>
                        <p class="text-gray-800 dark:text-gray-600 text-sm mb-4 mx-4">
                            {{ friend.url }}
                        </p>
                        <img class="absolute inset-0 w-full h-full object-cover opacity-20" :src="friend.avatar"
                            alt="avatar_background" />
                    </div>
                </a>
            </div>
        </div>
    </div>
</template>
